name: Build Test (with Artifacts)

on:
  workflow_dispatch:
    inputs:
      client_target:
        required: true
        type: choice
        default: test
        options:
          - live
          - test
          - emu

jobs:
  build:
    runs-on: windows-latest
    env:
      platform: "${{ inputs.client_target == 'emu' && 'Win32' || 'x64' }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout submodules excluding eqlib
        run: git -c submodule."src/eqlib".update=none submodule update --init --recursive --depth=1

      - name: Checkout ${{ inputs.client_target }} eqlib
        run: |
          git submodule update --init --remote "src\eqlib"
          git -C src/eqlib checkout ${{ inputs.client_target }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore src/MacroQuest.sln

      - name: vcpkg Cache
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: |
            contrib/vcpkg/buildtrees
            contrib/vcpkg/downloads
            contrib/vcpkg/installed
            contrib/vcpkg/packages
            contrib/vcpkg/vcpkg.exe
            contrib/vcpkg/vcpkg_mq_last_bootstrap*.txt
          key: ${{ runner.os }}-vcpkg-${{ env.platform }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-${{ env.platform }}-
            ${{ runner.os }}-vcpkg-

      - name: Build ${{ env.platform }} Release for ${{ inputs.client_target }}
        run: msbuild src/MacroQuest.sln /NoLogo /Verbosity:minimal /p:Configuration=Release /p:Platform=${{ env.platform }} /m /p:PreferredToolArchitecture=x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacroQuest-${{ inputs.client_target }}-${{ env.platform }}-${{ github.run_number }}
          path: |
            build/bin/Release/
          if-no-files-found: error
          retention-days: 7